services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: olympliance-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - DSN=${DSN}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - GO_ENVIRONMENT=${GO_ENVIRONMENT}
    restart: unless-stopped
