FROM golang:1.23 AS builder

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/server/main.go

FROM golang:1.23

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY --from=builder /app /app

EXPOSE 8080

CMD ["air"]
